export const FILTER_TYPES = {
  ALL: "ALL",
  COMPLETE: "COMPETE",
  UNCOMPLETE: "UNCOMPLETE"
};

export const SORTING_TYPES = {
  LEVEL: "LEVEL",
  PRIORITY: "PRIORITY",
  DATE: "DATE",
  INCR: "INCR",
  DECR: "DECR"
};
